import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.setViewportSize({ width: 1440, height: 900 });
await page.goto('http://localhost:5174', { waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
await page.screenshot({ path: '/tmp/about_section.png', clip: { x: 0, y: 900, width: 1440, height: 900 } });
await page.screenshot({ path: '/tmp/projects_section.png', clip: { x: 0, y: 1700, width: 1440, height: 900 } });
await page.screenshot({ path: '/tmp/full_page.png', fullPage: true });
await browser.close();
